### ISSUE TITLE
Solution from 2 station don't work

### ISSUE THREAD

**Issue by AntoWkill** [bluviolin/TrainMonitor#3]
Salve,
Volevo segnalarvi che da un paio di giorni nessun link di ricerca soluzioni tra due stazioni funziona.
Utilizzando il link di esempio presenti in github http://www.viaggiatreno.it/viaggiatrenonew/resteasy/viaggiatreno/soluzioniViaggioNew/228/458/2018-01-23T11:18:00

**Comment by gerryino** [comment]
Confermo, da alcuni giorni quell'API torna sempre una lista vuota.
La cosa curiosa è che è la stessa API usata dal viaggiatreno ufficiale, che difatti non funziona più: http://www.viaggiatreno.it/viaggiatrenonew/index.jsp
Bisognerebbe segnalarlo, ma non ho idea di come.

**Comment by AntoWkill** [comment]
Qualcuno ha idea di come segnalare il problema?

**Comment by AntoWkill** [comment]
Ho segnalato tramite la Live chat di trenitalia, ma DUBITO che abbiamo segnalato la cosa a qualcuno.

**Comment by roughconsensusandrunningcode** [comment]
Non solo la API, nemmeno la ricerca sul sito viaggiatreno funziona.

**Comment by gerryino** [comment]
Sto provando a chiedere in giro ma per ora nulla. 

Esistono sicuramente API alternative, visto che la mia app per i treni li trova ancora, ma io non le conosco...

**Comment by AntoWkill** [comment]
Se qualcuno ha una soluzione lo segnali per favore

**Comment by crisbal** [comment]
Un paio di spunti: per la ricerca e il tracciamento dei treni per Trenord è possibile usare l'API che usa l'applicazione mobile (c'è da fare un po' di reverse engineering con [mitmproxy](https://mitmproxy.org/) e l'unpinning dei certificati HTTPs). Se non esistono già documentate magari scriverò qualcosa a riguardo, la sto usando e funziona bene. 

Per quanto riguarda TrenItalia credo si possa usare la API che usa [il sito de lefrecce](lefrecce.it) ma sembra un po' più macchinosa. C'è già qualche progetto a riguardo: https://github.com/SimoDax/Trenitalia-API/wiki/API-Trenitalia---lefrecce.it

**Comment by AntoWkill** [comment]
L'API ha ricominciato a funzionare fortunatamente.
