### ISSUE TITLE
L'integrazione con HA non funziona piu' (404)

### ISSUE THREAD

**Issue by boggiano** [bluviolin/TrainMonitor#8]
Per esempio, la seguente URL:
http://www.viaggiatreno.it/viaggiatrenonew/resteasy/viaggiatreno/andamentoTreno/S00228/4640

riporta l'errore
"Error 404: Could not find resource for relative : /resteasy/viaggiatreno/andamentoTreno/S00228/4640 of full path: http://www.viaggiatreno.it/viaggiatrenonew/resteasy/viaggiatreno/andamentoTreno/S00228/4640"

Sembra che siano cambiati i path:
http://www.viaggiatreno.it/viaggiatrenonew/resteasy/
"Error 404: Could not find resource for full path: http://www.viaggiatreno.it/viaggiatrenonew/resteasy/ "

**Comment by roughconsensusandrunningcode** [comment]
Sono cambiati i parametri di alcune API, ho aggiornato la pagina wiki https://github.com/bluviolin/TrainMonitor/wiki/API-del-sistema-Viaggiatreno e invierò al più presto un commit col codice aggiornato

**Comment by boggiano** [comment]
Immaginavo!
Grazie mille.
