### ISSUE TITLE
modifica ricerca treni

### ISSUE THREAD

**Issue by lordfaber** [bluviolin/TrainMonitor#9]
Ma con la modifica delle api adesso è possibile associare una data di ricerca ad un treno ? ovvero il treno che circola magari solo in alcune date (ad esempio cercare il lunedi un treno che circola solo il venerdi ?)
grazie

**Comment by roughconsensusandrunningcode** [comment]
No, ho provato a fare ricerche con timestamp diverso da quello della data odierna e viene restituito `204 No Content`. È possibile che abbiano aggiunto il parametro della data perché prevedono di dare questa funzionalità in futuro, oppure si tratta di una funzione disponibile internamente ma non aperta pubblicamente. Solo solo mie supposizioni ovviamente.

**Comment by lordfaber** [comment]
ti ringrazio sei stato gentilissimo
la cosa strana è che per alcuni treni ti chiede se il giorno corrente o il giorno prima..
il timestamp esattamente cosa indica?  l orario in millisecondi a partire dalla mezzanotte ?

Inviato da iPhone
